package com.bonc.mrImsiBack.enums;

public enum LOG_PROCESSOR_COUNTER {

	MRLOCATE_imsiMatchCount, MRLOCATE_imsiNoMatchCount,

	MRLOCATE_MR_RECORDS,MRLOCATE_MR_WRONG_RECORDS,MRLOCATE_MR_COMBINE_RECORDS,

    MRLOCATE_XDR_RECORDS,MRLOCATE_XDR_WRONG_RECORDS,

	MRLOCATE_OTT_RECORDS,MRLOCATE_OTT_WRONG_RECORDS,

	MRLOCATE_mrottMatchCount, MRLOCATE_mrottNoMatchCount,

	COORDTRANS_SUCCESS_RECORES,COORDTRANS_ERR_RECORES,

	MRLOCATE_DATA_RECORDS,

	WC_MAP_WORD,WC_REDUCE_WORD

}
